### ISSUE TITLE
Reproducable crash using MidiSynth midi channel setting

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#111]
1. open menu item "Demo" -> "Midi Test".
2. play
3. hit a few notes on external midi keyboard (produces some sound output)
4. stop
5. change "Midi Test" midi channel to 2
6. play
7. hit a few notes on external midi keyboard -> crash
```
stefan@quadcorn:~/src/beast (master % u=)$ gdb --args /usr/local/beast/lib/beast-0-15/bin/beast-0.15.0 -p alsa=pulse
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/beast/lib/beast-0-15/bin/beast-0.15.0...fertig.
(gdb) r
Starting program: /usr/local/beast/lib/beast-0-15/bin/beast-0.15.0 -p alsa=pulse
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec2f4700 (LWP 28766)]
[New Thread 0x7fffebaf3700 (LWP 28767)]
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
[New Thread 0x7fffe924d700 (LWP 28768)]
[New Thread 0x7fffe8a4c700 (LWP 28769)]
[New Thread 0x7fffdbfff700 (LWP 28770)]
[Thread 0x7fffdbfff700 (LWP 28770) exited]
[New Thread 0x7fffdbfff700 (LWP 29745)]
[New Thread 0x7fffdaaba700 (LWP 29746)]
[Thread 0x7fffdbfff700 (LWP 29745) exited]
[Thread 0x7fffdaaba700 (LWP 29746) exited]
[New Thread 0x7fffdaaba700 (LWP 29747)]
[New Thread 0x7fffdbfff700 (LWP 29748)]
[New Thread 0x7fffda2b9700 (LWP 29749)]
[New Thread 0x7fffd9ab8700 (LWP 29750)]
[New Thread 0x7fffd92b7700 (LWP 29751)]
[New Thread 0x7fffd8ab6700 (LWP 29752)]
[New Thread 0x7fffbffff700 (LWP 29753)]
[New Thread 0x7fffbf7fe700 (LWP 29754)]
[New Thread 0x7fffbeffd700 (LWP 29755)]
[New Thread 0x7fffbe7fc700 (LWP 29756)]
[New Thread 0x7fffbdffb700 (LWP 29757)]
[New Thread 0x7fffbd7fa700 (LWP 29758)]
[New Thread 0x7fffbcff9700 (LWP 29759)]
[New Thread 0x7fff8bfff700 (LWP 29760)]
[New Thread 0x7fff8b7fe700 (LWP 29761)]
[New Thread 0x7fff8affd700 (LWP 29762)]
[New Thread 0x7fff8a7fc700 (LWP 29763)]
beast-0.15.0: ignoring note-on (783.990845Hz) for foreign midi channel: 1
beast-0.15.0: ignoring note-on (698.456482Hz) for foreign midi channel: 1
beast-0.15.0: ignoring note-on (523.251160Hz) for foreign midi channel: 1
beast-0.15.0: ignoring note-on (440.000000Hz) for foreign midi channel: 1
beast-0.15.0: ignoring note-on (523.251160Hz) for foreign midi channel: 1
beast-0.15.0: ignoring note-on (493.883301Hz) for foreign midi channel: 1
beast-0.15.0: ignoring note-on (659.255127Hz) for foreign midi channel: 1
[Thread 0x7fffdaaba700 (LWP 29747) exited]
[New Thread 0x7fffdaaba700 (LWP 32028)]
[New Thread 0x7fff89ba5700 (LWP 32029)]
[Thread 0x7fffdaaba700 (LWP 32028) exited]
[Thread 0x7fff89ba5700 (LWP 32029) exited]
[New Thread 0x7fff89ba5700 (LWP 32030)]
beast-0.15.0: ignoring note-on (698.456482Hz) for foreign midi channel: 1

Thread 3 "BseSequencer" received signal SIGSEGV, Segmentation fault.
[Wechseln zu Thread 0x7fffebaf3700 (LWP 28767)]
0x00007ffff7848626 in (anonymous namespace)::MidiChannel::no_poly_voice (this=0x7fffe505f8e0, noteon=true, event_name=0x7ffff7bf45e5 "note-on", freq=698.456482)
    at bse/bsemidireceiver.cc:1110
1110              if (bse_module_is_scheduled (mchannel->voices[i]->vmodule))
(gdb) bt
#0  0x00007ffff7848626 in (anonymous namespace)::MidiChannel::no_poly_voice(bool, char const*, float) (this=0x7fffe505f8e0, noteon=true, event_name=0x7ffff7bf45e5 "note-on", freq=698.456482) at bse/bsemidireceiver.cc:1110
#1  0x00007ffff7848b4e in (anonymous namespace)::MidiChannel::start_note(guint64, gfloat, gfloat, BseTrans*) (this=0x7fffe505f8e0, tick_stamp=2132723, freq=698.456482, velocity=0.629921257, trans=0x7fffdc003908) at bse/bsemidireceiver.cc:1200
#2  0x00007ffff784c340 in midi_receiver_process_event_L(BseMidiReceiver*, guint64) (self=0x7fffe4a66a70, max_tick_stamp=2132723) at bse/bsemidireceiver.cc:2120
#3  0x00007ffff784942e in bse_midi_receiver_farm_process_events(unsigned long) (max_tick_stamp=2132723) at bse/bsemidireceiver.cc:1340
#4  0x00007ffff7838692 in bse_midi_decoder_push_data(BseMidiDecoder*, unsigned int, unsigned char*, unsigned long) (self=0x7fffe4fe3da0, n_bytes=3, bytes=0x7fffebaf0930 "\220MP\370\370\370\370", <incomplete sequence \370>, usec_systime=1564761430915594) at bse/bsemididecoder.cc:303
#5  0x00007fffeabcf480 in alsa_midi_io_handler(gpointer, guint, GPollFD*) (data=0x7fffe5072460, n_pfds=1, pfds=0x7fffebaf2958) at drivers/bsemididevice-alsa.cc:312
#6  0x00007ffff789fde8 in Bse::Sequencer::pool_poll_Lm(int) (this=0x7fffe40932f0, timeout_ms=-1) at bse/bsesequencer.cc:220
#7  0x00007ffff78a0c1c in Bse::Sequencer::sequencer_thread() (this=0x7fffe40932f0) at bse/bsesequencer.cc:391
#8  0x00007ffff78a4eaf in std::__invoke_impl<void, void (Bse::Sequencer::*)(), Bse::Sequencer*>(std::__invoke_memfun_deref, void (Bse::Sequencer::*&&)(), Bse::Sequencer*&&) (__f=@0x7fffe4089330: (void (Bse::Sequencer::*)(Bse::Sequencer * const)) 0x7ffff78a063e <Bse::Sequencer::sequencer_thread()>, __t=@0x7fffe4089328: 0x7fffe40932f0)
    at /usr/include/c++/7/bits/invoke.h:73
#9  0x00007ffff78a38d7 in std::__invoke<void (Bse::Sequencer::*)(), Bse::Sequencer*>(void (Bse::Sequencer::*&&)(), Bse::Sequencer*&&) (__fn=@0x7fffe4089330: (void (Bse::Sequencer::*)(Bse::Sequencer * const)) 0x7ffff78a063e <Bse::Sequencer::sequencer_thread()>, __args#0=@0x7fffe4089328: 0x7fffe40932f0) at /usr/include/c++/7/bits/invoke.h:95
#10 0x00007ffff78a830d in std::thread::_Invoker<std::tuple<void (Bse::Sequencer::*)(), Bse::Sequencer*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x7fffe4089328)
    at /usr/include/c++/7/thread:234
#11 0x00007ffff78a8298 in std::thread::_Invoker<std::tuple<void (Bse::Sequencer::*)(), Bse::Sequencer*> >::operator()() (this=0x7fffe4089328) at /usr/include/c++/7/thread:243
#12 0x00007ffff78a8255 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Bse::Sequencer::*)(), Bse::Sequencer*> > >::_M_run() (this=0x7fffe4089320)
    at /usr/include/c++/7/thread:186
#13 0x00007ffff5a4a66f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff51bf6db in start_thread (arg=0x7fffebaf3700) at pthread_create.c:463
#15 0x00007ffff4ee888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/)
