### ISSUE TITLE
Crash on part deletion

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#32]
Beast always crashes if I delete a part. To reproduce
 - open party monster
 - delete some part in track view

```
Thread 2 "Beast GUI" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb953700 (LWP 20887)]
Bse::SongImpl::find_any_track_for_part (this=<optimized out>, part=...) at bsesong.cc:778
778       return track->as<TrackIfaceP> ();
(gdb) bt
#0  Bse::SongImpl::find_any_track_for_part (this=<optimized out>, part=...) at bsesong.cc:778
#1  0x00007ffff7922781 in Bse::__aida_call__Song__find_any_track_for_part (fbr=...) at bseapi_interfaces.cc:6361
#2  0x00007ffff7a2d816 in Aida::ServerConnectionImpl::dispatch (this=0x7fffe409cf20) at ../aidacc/aida.cc:3356
#3  0x00007ffff77b7847 in Bse::AidaGlibSourceImpl::dispatch (this=<optimized out>, this=<optimized out>) at bsestartup.cc:114
#4  Bse::AidaGlibSourceImpl::glib_dispatch (src=<optimized out>) at bsestartup.cc:85
#5  0x00007ffff6120197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff61203f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff612049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff782c7ae in bse_main_loop_thread (init_queue=<optimized out>) at bsemain.cc:222
#9  0x00007ffff5447c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff5ec06ba in start_thread (arg=0x7fffeb953700) at pthread_create.c:333
#11 0x00007ffff4bad41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:10
(gdb)
```

Possibly related to https://github.com/tim-janik/beast/issues/24

**Comment by tim-janik** [comment]
Thanks for the report, fixed with:

commit ba21e192ce82e143de32e1ff74ac85fb1f76c56b
Date:   Thu Mar 8 01:20:32 2018 +0100
    Merge branch 'destruction-guards'
