### ISSUE TITLE
Reproducable crash with mono voice count

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#37]
I'm not really sure as to why this is happening, but this is a reproducable crash. It can be triggered as
follows:

 - load portamento mini demo (from portamento branch)
 - we can reproduce this with the first track only (so you can delete every track except lead track)
- set lead track num voices to 24
- press play
- stop after a while
- set lead track num voices to 1
- press play

beast will crash now.

gdb output:
```
Thread 3 "Beast GUI" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeaaf4700 (LWP 17198)]
0x00007ffff784279c in (anonymous namespace)::MidiChannel::no_poly_voice (this=this@entry=0x7fffe4444eb0, noteon=noteon@entry=true, event_name=event_name@entry=0x7ffff7acf6b6 "note-on", freq=493.883301)
    at bsemidireceiver.cc:1083
1083              if (bse_module_is_scheduled (mchannel->voices[i]->vmodule))
(gdb) bt
#0  0x00007ffff784279c in (anonymous namespace)::MidiChannel::no_poly_voice (this=this@entry=0x7fffe4444eb0, noteon=noteon@entry=true, event_name=event_name@entry=0x7ffff7acf6b6 "note-on", freq=493.883301)
    at bsemidireceiver.cc:1083
#1  0x00007ffff7844288 in (anonymous namespace)::MidiChannel::start_note (trans=0x7fffdc001648, velocity=<optimized out>, freq=<optimized out>, tick_stamp=223713, this=<optimized out>)
    at bsemidireceiver.cc:1173
#2  midi_receiver_process_event_L (self=self@entry=0x7fffe444f6c0, max_tick_stamp=max_tick_stamp@entry=223893) at bsemidireceiver.cc:2096
#3  0x00007ffff7845947 in bse_midi_receiver_process_events (self=self@entry=0x7fffe444f6c0, max_tick_stamp=max_tick_stamp@entry=223893) at bsemidireceiver.cc:1353
#4  0x00007ffff78aa047 in Bse::Sequencer::process_song_unlooped_SL (this=this@entry=0x7fffe400df30, song=song@entry=0x7fffe470a000, n_ticks=n_ticks@entry=3, force_active_tracks=force_active_tracks@entry=true)
    at bsesequencer.cc:416
#5  0x00007ffff78aa20c in Bse::Sequencer::process_song_SL (this=this@entry=0x7fffe400df30, song=song@entry=0x7fffe470a000, n_ticks=<optimized out>) at bsesequencer.cc:432
#6  0x00007ffff78aa5ce in Bse::Sequencer::sequencer_thread (this=0x7fffe400df30) at bsesequencer.cc:370
#7  0x00007ffff5442c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff5ebb6ba in start_thread (arg=0x7fffeaaf4700) at pthread_create.c:333
#9  0x00007ffff4ba841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/)
