### ISSUE TITLE
Crash on removing song post proc network

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#39]
Steps to reproduce:

 - open party monster
 - go to song properties tab
 - remove Postprocesser (which is currently Compression)

Crashes like this:

```
beast-0.11.1: ../aidacc/aida.cc:2340: const Aida::RemoteHandle& Aida::assert_remote_handle(const Aida::RemoteHandle&): Assertion `remote_handle != NULL' failed.

Thread 1 "Beast GUI" received signal SIGABRT, Aborted.
0x00007ffff4ad6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4ad6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff4ad802a in __GI_abort () at abort.c:89
#2  0x00007ffff4acebd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff7ad530a "remote_handle != NULL", file=file@entry=0x7ffff7ad52f8 "../aidacc/aida.cc", line=line@entry=2340, 
    function=function@entry=0x7ffff7ad79a0 <Aida::assert_remote_handle(Aida::RemoteHandle const&)::__PRETTY_FUNCTION__> "const Aida::RemoteHandle& Aida::assert_remote_handle(const Aida::RemoteHandle&)")
    at assert.c:92
#3  0x00007ffff4acec82 in __GI___assert_fail (assertion=assertion@entry=0x7ffff7ad530a "remote_handle != NULL", file=file@entry=0x7ffff7ad52f8 "../aidacc/aida.cc", line=line@entry=2340, 
    function=function@entry=0x7ffff7ad79a0 <Aida::assert_remote_handle(Aida::RemoteHandle const&)::__PRETTY_FUNCTION__> "const Aida::RemoteHandle& Aida::assert_remote_handle(const Aida::RemoteHandle&)")
    at assert.c:101
#4  0x00007ffff770476c in Aida::assert_remote_handle (remote_handle=...) at ../aidacc/aida.cc:2340
#5  0x00007ffff7a1abd7 in Aida::assert_remote_handle (remote_handle=...) at ../aidacc/aida.cc:2356
#6  Aida::ProtoScopeCall2Way::ProtoScopeCall2Way (this=0x7fffffffbd1f, pm=..., rhandle=..., hashi=<optimized out>, hashlo=<optimized out>) at ../aidacc/aida.cc:2352
#7  0x00007ffff779e7d6 in Bse::ObjectHandle::proxy_id (this=this@entry=0x7fffffffbd80) at bseapi_handles.cc:628
#8  0x00000000004df24f in param_proxy_changed (entry=<optimized out>, param=0xd9a650) at bstparam-proxy.cc:150
#9  0x00007ffff63f1fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6403fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff640bd41 in g_signal_emitv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6dd91f8 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#13 0x00007ffff6dd9721 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x00007ffff6dd9994 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#15 0x00007ffff6ddaa91 in gtk_bindings_activate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#16 0x00007ffff6e1faa8 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#17 0x00007ffff6e8aaec in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#18 0x00007ffff63f1eff in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff640456e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff640c7f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff640d08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff6fa293c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#23 0x00007ffff6fb640d in gtk_window_propagate_key_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x000000000055cd43 in gxk_dialog_key_press_event (widget=0xba0200, event=0x1a04730) at gxkdialog.cc:537
#25 0x00007ffff6e8aaec in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#26 0x00007ffff63f1fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff640456e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff640c7f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff640d08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff6fa293c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#31 0x00007ffff6e89367 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#32 0x00007ffff6e8963b in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#33 0x00007ffff6afdc8c in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#34 0x00007ffff611b197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff611b3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff611b49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00000000005493cf in Bst::event_loop_run () at bstutils.cc:42
#38 0x000000000055660c in main_loop (self=<optimized out>, args=<optimized out>) at bstmain.cc:502
#39 0x00007ffff59d8971 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#40 0x00007ffff5b0e05c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#41 0x00007ffff59cfda9 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#42 0x00007ffff5a4a09e in PyRun_FileExFlags () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#43 0x00007ffff5a4b6e7 in PyRun_SimpleFileExFlags () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#44 0x0000000000557430 in main_run_event_loop () at bstmain.cc:526
#45 0x0000000000446f44 in main (argc=1, argv=0x7fffffffd7b8) at bstmain.cc:150
```

**Comment by tim-janik** [comment]
Thanks, fixed with commit d034737a86b2fec1ed02c2b3187b60a491a6a1cc:
Date:   Tue Apr 3 19:15:03 2018 +0200
    BEAST-GTK: bstparam-proxy: fix missing NULL handle guard
